import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { Checkbox } from "@/components/ui/checkbox";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Info } from "lucide-react";

interface InfoDialogProps {
  showInfoDialog: boolean;
  setShowInfoDialog: (showInfoDialog: boolean) => void;
}

function InfoDialog({ showInfoDialog, setShowInfoDialog }: InfoDialogProps) {
  return (
    <Dialog open={showInfoDialog}>
      <DialogTrigger asChild>
        <Button
          variant="circular"
          id="info-button"
          size="icon"
          onClick={() => setShowInfoDialog(true)}
        >
          <Info />
        </Button>
      </DialogTrigger>
      <DialogContent>
        <DialogHeader>
          <DialogTitle className="text-xl">
            Welcome to Canvas Forge!
          </DialogTitle>
          <DialogDescription className="text-md flex flex-col gap-2">
            <p>
              Curious about the power of the HTML Canvas API but not sure where
              to start with the code? Or perhaps you want to deepen your
              understanding in a more intuitive way?
            </p>
            <p>
              Canvas Forge is designed as your interactive guide and learning
              companion. The core idea is visual first: you learn by doing!
              Explore the fundamental concepts and capabilities of the HTML
              Canvas API directly through easy-to-use on-screen menus and tools
              – absolutely no coding is required to begin your learning journey!
            </p>
            <p>
              Use the visual interface to draw shapes, add and manipulate
              images, explore animation techniques, manage layers, resize the
              canvas, and experiment with a wide array of Canvas features. As
              you interact visually, you'll build an intuitive understanding of
              how these elements work on the web.
            </p>
            <p>
              Ready to see how your visual steps translate? Switch to the "Code
              View". Here, you'll discover the clean, well-structured HTML and
              JavaScript code that was generated by your visual actions. This
              view is perfect for seeing the code behind your creations, helping
              you connect the visual outcome to the specific API calls. While
              you can't edit the code directly within the Forge, it's generated
              for you to easily copy and paste directly into your own web
              projects.
            </p>
            <p>
              Use Canvas Forge to learn the Canvas API through visual
              exploration, understand the code it generates, and then use that
              code as a foundation to build your own projects. Dive in, explore
              the tools, and start forging your knowledge (and creations!) on
              the Canvas today! Have fun learning and building!
            </p>
            <div className="flex flex-row gap-2 items-center ">
              <Checkbox id="show-modal-checkbox" />
              <Label
                htmlFor="show-modal-checkbox"
                className="text-sm text-primary"
              >
                Don't show this again
              </Label>
            </div>
          </DialogDescription>
        </DialogHeader>

        <DialogFooter>
          <Button variant="default" onClick={() => setShowInfoDialog(false)}>
            Close
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

export { InfoDialog };
