function LeftViewPanel() {
  return (
    <section>
      <div>
        <div>
          <div>CanvasView</div>
          <div>CodeView</div>
        </div>
        <div>SplitView</div>
      </div>
      <div>
        <canvas id="myCanvas">
          Your browser does not support the HTML5 canvas element.
        </canvas>
      </div>
      <div>This is the code that was generated by your visual actions.</div>
    </section>
  );
}

export { LeftViewPanel };
